### PR TITLE
Feat/custom network support

### PR DESCRIPTION
**Pull request by ginnun**
Custom network support is needed for Lace end-to-end tests.

### CODE REVIEW

**Review by slowbackspace — APPROVED** [review]
lgtm

**Comment by vladimirvolek** [comment]
@ginnun, Please please could you add this update to our changelog?

**Review by vladimirvolek — APPROVED** [review]

**Comment by ginnun** [comment]
> @ginnun, Please please could you add this update to our changelog?

Done in ad84cedb6b223058f2ecc72a27f80545cbfd7b67

**Review by slowbackspace — APPROVED** [review]

**Comment by vladimirvolek** [comment]
https://github.com/blockfrost/blockfrost-backend-ryo/commit/79ebea8fca2e1a99d5d2d92a8590da36ddc5f9a7

**Pull request merged**
