### PR TITLE
feat: custom network

### PR DESCRIPTION
**Pull request by vladimirvolek**
Resolves: https://github.com/blockfrost/blockfrost-backend-ryo/issues/72

### CODE REVIEW

**Comment by lemmon-714** [comment]
Can I assist somehow? Really need this

**Comment by sorki** [comment]
We are considering handling cardano-node accepted genesis files so users wouldn't have to convert to our custom format - would that be helpful?

**Comment by lemmon-714** [comment]
As long as it allows setting up of a rudimentary private testnet with a blockfrost instance it's fine by me. Sounds like a good approach.

**Comment by sorki** [comment]
I wonder if it's also safe to assume that people running custom networks use InstaFork (https://input-output-hk.github.io/cardano-wallet/design/Eras) to fork into latest era on epoch 0. That's the only parameter which is not available in genesis configs (the epoch number of the transition from Byron -> Shelley or at least it would require node config file if InstaFork is used) and it only affects `/network/eras` endpoint.

**Comment by vladimirvolek** [comment]
Also, should we just disable the validation?

**Comment by sorki** [comment]
@lemmon-714 can you test using this PR?

**Comment by klntsky** [comment]
What needs to be done to make this PR ready for review?

**Comment by sorki** [comment]
> What needs to be done to make this PR ready for review?

It is pretty much ready, would be nice if someone could test it. @lemmon-714 had some troubles setting it up so not sure if he managed to test it.

**Comment by lemmon-714** [comment]
> > What needs to be done to make this PR ready for review?
> 
> It is pretty much ready, would be nice if someone could test it. @lemmon-714 had some troubles setting it up so not sure if he managed to test it.

Switched to another approach for now. Might return to this later though.

**Comment by vladimirvolek** [comment]
> > > What needs to be done to make this PR ready for review?
> > 
> > 
> > It is pretty much ready, would be nice if someone could test it. @lemmon-714 had some troubles setting it up so not sure if he managed to test it.
> 
> Switched to another approach for now. Might return to this later though.

Okay I will close this for now. Feel free to reopen the issue.

**Pull request closed without merging**
